### ISSUE TITLE
打包后APP闪退

### ISSUE THREAD

**Issue by jiangheng90** [jadennn/flutter_ijk#13]
使用你的插件写了一个海康威视云台控制的demo，在模拟器上APP没问题，打包debug和release版本在手机上都闪退。无任何报错。Target版本是Android Q API 29 最低API 16

**Comment by jiangheng90** [comment]
暂时我没法找到原因。。。。

**Comment by angwangiot** [comment]
@jiangheng90 你好，我也想用这个来看海康威视的视频，但是云台控制你是怎么实现的，还有历史录像的查询呢（RTSP可以点播历史录像，这里的意思是历史录像时间段查询），希望能得到你的指点，谢谢

**Comment by jadennn** [comment]
> 使用你的插件写了一个海康威视云台控制的demo，在模拟器上APP没问题，打包debug和release版本在手机上都闪退。无任何报错。Target版本是Android Q API 29 最低API 16

打包的app里面带有ijkplayer的库吗？我怀疑是缺少库导致的

**Comment by jiangheng90** [comment]
> > 使用你的插件写了一个海康威视云台控制的demo，在模拟器上APP没问题，打包debug和release版本在手机上都闪退。无任何报错。Target版本是Android Q API 29 最低API 16
> 
> 打包的app里面带有ijkplayer的库吗？我怀疑是缺少库导致的

好吧，果然是这样 
https://blog.csdn.net/coder_pig/article/details/79134625
需要按这个教程编译so库然后放入项目就好了吧？

**Comment by jadennn** [comment]
> > > 使用你的插件写了一个海康威视云台控制的demo，在模拟器上APP没问题，打包debug和release版本在手机上都闪退。无任何报错。Target版本是Android Q API 29 最低API 16
> > 
> > 
> > 打包的app里面带有ijkplayer的库吗？我怀疑是缺少库导致的
> 
> 好吧，果然是这样
> https://blog.csdn.net/coder_pig/article/details/79134625
> 需要按这个教程编译so库然后放入项目就好了吧？

不用自己编译，你现在是怎么引用flutter_ijk的呢？一般来说会自带库文件的

**Comment by jiangheng90** [comment]
> > > > 使用你的插件写了一个海康威视云台控制的demo，在模拟器上APP没问题，打包debug和release版本在手机上都闪退。无任何报错。Target版本是Android Q API 29 最低API 16
> > > 
> > > 
> > > 打包的app里面带有ijkplayer的库吗？我怀疑是缺少库导致的
> > 
> > 
> > 好吧，果然是这样
> > https://blog.csdn.net/coder_pig/article/details/79134625
> > 需要按这个教程编译so库然后放入项目就好了吧？
> 
> 不用自己编译，你现在是怎么引用flutter_ijk的呢？一般来说会自带库文件的

在pubspec.yaml中添加
 flutter_ijk:
    git:
      url: https://github.com/jadennn/flutter_ijk
引入的

**Comment by jiangheng90** [comment]
> @jiangheng90 你好，我也想用这个来看海康威视的视频，但是云台控制你是怎么实现的，还有历史录像的查询呢（RTSP可以点播历史录像，这里的意思是历史录像时间段查询），希望能得到你的指点，谢谢

可以参考他们的官方文档https://open.ys7.com/doc/zh/
具体还看你们的设备是否连了萤石云

**Comment by angwangiot** [comment]
@jiangheng90 了解了，谢谢，我的情况不一样，我这边用的是海康的局域网NVR，不是萤石云。

**Comment by jadennn** [comment]
> > > > > 使用你的插件写了一个海康威视云台控制的demo，在模拟器上APP没问题，打包debug和release版本在手机上都闪退。无任何报错。Target版本是Android Q API 29 最低API 16
> > > > 
> > > > 
> > > > 打包的app里面带有ijkplayer的库吗？我怀疑是缺少库导致的
> > > 
> > > 
> > > 好吧，果然是这样
> > > https://blog.csdn.net/coder_pig/article/details/79134625
> > > 需要按这个教程编译so库然后放入项目就好了吧？
> > 
> > 
> > 不用自己编译，你现在是怎么引用flutter_ijk的呢？一般来说会自带库文件的
> 
> 在pubspec.yaml中添加
> flutter_ijk:
> git:
> url: https://github.com/jadennn/flutter_ijk
> 引入的

兄弟，加个微信吧，这样沟通起来好慢。。（15013833595）

**Comment by Mokyyds** [comment]
> @jiangheng90 了解了，谢谢，我的情况不一样，我这边用的是海康的局域网NVR，不是萤石云。

请问你找到解决方案了嘛？我们也需要局域网控制云台，但看网上的方法都得通过萤石云来控制，怎么解决呢？

**Comment by angwangiot** [comment]
> 
> 
> > @jiangheng90 了解了，谢谢，我的情况不一样，我这边用的是海康的局域网NVR，不是萤石云。
> 
> 请问你找到解决方案了嘛？我们也需要局域网控制云台，但看网上的方法都得通过萤石云来控制，怎么解决呢？

局域网控制云台有几种思路，主要还是看网络情况。
如果APP与摄像头在同一个局域网，可以考虑自己封装海康的SDK到flutter，然后调用函数。
如果感觉自己在移动端封装太复杂，就通过后台封装中转，在后台调用海康的SDK进行控制，然后对app端提供接口，app调用接口后，后台再根据SDK调用摄像头的控制。
如果不在一个局域网就比较麻烦了，可以通过VPN的方式建立虚拟专用网来保证网络通信没问题。或者在摄像头那边再放一个模块，用于将网络或一些转换成反向主动连接后台服务器的。

**Comment by Mokyyds** [comment]
> > > @jiangheng90 了解了，谢谢，我的情况不一样，我这边用的是海康的局域网NVR，不是萤石云。
> > 
> > 
> > 请问你找到解决方案了嘛？我们也需要局域网控制云台，但看网上的方法都得通过萤石云来控制，怎么解决呢？
> 
> 局域网控制云台有几种思路，主要还是看网络情况。
> 如果APP与摄像头在同一个局域网，可以考虑自己封装海康的SDK到flutter，然后调用函数。
> 如果感觉自己在移动端封装太复杂，就通过后台封装中转，在后台调用海康的SDK进行控制，然后对app端提供接口，app调用接口后，后台再根据SDK调用摄像头的控制。
> 如果不在一个局域网就比较麻烦了，可以通过VPN的方式建立虚拟专用网来保证网络通信没问题。或者在摄像头那边再放一个模块，用于将网络或一些转换成反向主动连接后台服务器的。

是在同一个局域网的，但我看萤石云提供的SDK都需要他们后台的token，如何封装成局域网能直接使用的形式呢？有没有相关的资料可以参考一下，谢谢！

**Comment by angwangiot** [comment]
> 
> 
> > > > @jiangheng90 了解了，谢谢，我的情况不一样，我这边用的是海康的局域网NVR，不是萤石云。
> > > 
> > > 
> > > 请问你找到解决方案了嘛？我们也需要局域网控制云台，但看网上的方法都得通过萤石云来控制，怎么解决呢？
> > 
> > 
> > 局域网控制云台有几种思路，主要还是看网络情况。
> > 如果APP与摄像头在同一个局域网，可以考虑自己封装海康的SDK到flutter，然后调用函数。
> > 如果感觉自己在移动端封装太复杂，就通过后台封装中转，在后台调用海康的SDK进行控制，然后对app端提供接口，app调用接口后，后台再根据SDK调用摄像头的控制。
> > 如果不在一个局域网就比较麻烦了，可以通过VPN的方式建立虚拟专用网来保证网络通信没问题。或者在摄像头那边再放一个模块，用于将网络或一些转换成反向主动连接后台服务器的。
> 
> 是在同一个局域网的，但我看萤石云提供的SDK都需要他们后台的token，如何封装成局域网能直接使用的形式呢？有没有相关的资料可以参考一下，谢谢！

局域网可以不使用萤石云的SDK啊，海康威视本身有SDK的，为啥必须用萤石云系列的？

**Comment by Mokyyds** [comment]
> > > > > @jiangheng90 了解了，谢谢，我的情况不一样，我这边用的是海康的局域网NVR，不是萤石云。
> > > > 
> > > > 
> > > > 请问你找到解决方案了嘛？我们也需要局域网控制云台，但看网上的方法都得通过萤石云来控制，怎么解决呢？
> > > 
> > > 
> > > 局域网控制云台有几种思路，主要还是看网络情况。
> > > 如果APP与摄像头在同一个局域网，可以考虑自己封装海康的SDK到flutter，然后调用函数。
> > > 如果感觉自己在移动端封装太复杂，就通过后台封装中转，在后台调用海康的SDK进行控制，然后对app端提供接口，app调用接口后，后台再根据SDK调用摄像头的控制。
> > > 如果不在一个局域网就比较麻烦了，可以通过VPN的方式建立虚拟专用网来保证网络通信没问题。或者在摄像头那边再放一个模块，用于将网络或一些转换成反向主动连接后台服务器的。
> > 
> > 
> > 是在同一个局域网的，但我看萤石云提供的SDK都需要他们后台的token，如何封装成局域网能直接使用的形式呢？有没有相关的资料可以参考一下，谢谢！
> 
> 局域网可以不使用萤石云的SDK啊，海康威视本身有SDK的，为啥必须用萤石云系列的？

谢谢指点，我在海康威视的SDK文档中找到了要实现的方法，但是他们没提供Android的SDK怎么办呢？我看官网只有Windows和Linux两个版本

**Comment by angwangiot** [comment]
> 
> 
> > > > > > @jiangheng90 了解了，谢谢，我的情况不一样，我这边用的是海康的局域网NVR，不是萤石云。
> > > > > 
> > > > > 
> > > > > 请问你找到解决方案了嘛？我们也需要局域网控制云台，但看网上的方法都得通过萤石云来控制，怎么解决呢？
> > > > 
> > > > 
> > > > 局域网控制云台有几种思路，主要还是看网络情况。
> > > > 如果APP与摄像头在同一个局域网，可以考虑自己封装海康的SDK到flutter，然后调用函数。
> > > > 如果感觉自己在移动端封装太复杂，就通过后台封装中转，在后台调用海康的SDK进行控制，然后对app端提供接口，app调用接口后，后台再根据SDK调用摄像头的控制。
> > > > 如果不在一个局域网就比较麻烦了，可以通过VPN的方式建立虚拟专用网来保证网络通信没问题。或者在摄像头那边再放一个模块，用于将网络或一些转换成反向主动连接后台服务器的。
> > > 
> > > 
> > > 是在同一个局域网的，但我看萤石云提供的SDK都需要他们后台的token，如何封装成局域网能直接使用的形式呢？有没有相关的资料可以参考一下，谢谢！
> > 
> > 
> > 局域网可以不使用萤石云的SDK啊，海康威视本身有SDK的，为啥必须用萤石云系列的？
> 
> 谢谢指点，我在海康威视的SDK文档中找到了要实现的方法，但是他们没提供Android的SDK怎么办呢？我看官网只有Windows和Linux两个版本

你可以找海康的售后要，针对Android和IOS的版本，或者留个邮箱，我发你。

**Comment by Mokyyds** [comment]
> > > > > > > @jiangheng90 了解了，谢谢，我的情况不一样，我这边用的是海康的局域网NVR，不是萤石云。
> > > > > > 
> > > > > > 
> > > > > > 请问你找到解决方案了嘛？我们也需要局域网控制云台，但看网上的方法都得通过萤石云来控制，怎么解决呢？
> > > > > 
> > > > > 
> > > > > 局域网控制云台有几种思路，主要还是看网络情况。
> > > > > 如果APP与摄像头在同一个局域网，可以考虑自己封装海康的SDK到flutter，然后调用函数。
> > > > > 如果感觉自己在移动端封装太复杂，就通过后台封装中转，在后台调用海康的SDK进行控制，然后对app端提供接口，app调用接口后，后台再根据SDK调用摄像头的控制。
> > > > > 如果不在一个局域网就比较麻烦了，可以通过VPN的方式建立虚拟专用网来保证网络通信没问题。或者在摄像头那边再放一个模块，用于将网络或一些转换成反向主动连接后台服务器的。
> > > > 
> > > > 
> > > > 是在同一个局域网的，但我看萤石云提供的SDK都需要他们后台的token，如何封装成局域网能直接使用的形式呢？有没有相关的资料可以参考一下，谢谢！
> > > 
> > > 
> > > 局域网可以不使用萤石云的SDK啊，海康威视本身有SDK的，为啥必须用萤石云系列的？
> > 
> > 
> > 谢谢指点，我在海康威视的SDK文档中找到了要实现的方法，但是他们没提供Android的SDK怎么办呢？我看官网只有Windows和Linux两个版本
> 
> 你可以找海康的售后要，针对Android和IOS的版本，或者留个邮箱，我发你。

非常感谢！如果有文档的话更好了。zhoutaolei@gmail.com
