### ISSUE TITLE
播放rtsp流的视频，有画面但是没有声音

### ISSUE THREAD

**Issue by jiny02** [jadennn/flutter_ijk#15]
例如这个 rtsp://113.136.42.39:554/PLTV/88888888/224/3221226031/10000100000000060000000001537275_0.smil

**Comment by jiny02** [comment]
iOS和Android都没有声音

**Comment by jadennn** [comment]
兄弟，你这个音频格式是mp2的，之前是不支持的，新版本已经支持了，可以直接使用。
至于具体的修改方法，参考本项目文档的源码编译过程，在module.sh里面增加mp2解码器，
`export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mp2"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mp2float" `
然后分别编译Android的so库和IOS的framework文件，同步到项目即可，以后有其他的不支持的请参考同样的方法，，本项目不能够确保全格式支持。
