### ISSUE TITLE
copyPixelBuffer不调用问题

### ISSUE THREAD

**Issue by abyConnor** [jadennn/flutter_ijk#2]
当视频播放出来过后，一直有声音，无画面。copyPixelBuffer并没有调用，想请问一下，你知道怎么回事吗

**Comment by jadennn** [comment]
我在吃饭，下午看看这个问题


| |
杨玉
邮箱：email_jade@163.com
|

签名由 网易邮箱大师 定制

在2019年02月21日 11:53，qiang.zhou 写道：

当视频播放出来过后，一直有声音，无画面。copyPixelBuffer并没有调用，想请问一下，你知道怎么回事吗

**Comment by jadennn** [comment]
> 当视频播放出来过后，一直有声音，无画面。copyPixelBuffer并没有调用，想请问一下，你知道怎么回事吗

你是用的真机还是模拟器？

**Comment by Herryjoeson** [comment]
老哥我再真机下iphone7 copyPixelBuffer并没有调用
