### ISSUE TITLE
Warning when combining with video_player plugin

### ISSUE THREAD

**Issue by ened** [jadennn/flutter_ijk#6]
```
objc[35184]: Class FLTFrameUpdater is implemented in both 
/private/var/containers/Bundle/Application/C860D20D-BAB9-4EC5-B2C3-3A96411E9C7B/Runner.app/Frameworks/video_player.framework/video_player (0x1056aa0e0) and
/private/var/containers/Bundle/Application/C860D20D-BAB9-4EC5-B2C3-3A96411E9C7B/Runner.app/Frameworks/flutter_ijk.framework/flutter_ijk (0x1050a0b08). 
One of the two will be used. Which one is undefined.

objc[35184]: Class FLTVideoPlayer is implemented in both 
/private/var/containers/Bundle/Application/C860D20D-BAB9-4EC5-B2C3-3A96411E9C7B/Runner.app/Frameworks/video_player.framework/video_player (0x1056aa108) and 
/private/var/containers/Bundle/Application/C860D20D-BAB9-4EC5-B2C3-3A96411E9C7B/Runner.app/Frameworks/flutter_ijk.framework/flutter_ijk (0x1050a0b30).
One of the two will be used. Which one is undefined.
```

This happens on iOS projects that include both `video_player` and `flutter_ijk`.

**Comment by jadennn** [comment]
> ```
> objc[35184]: Class FLTFrameUpdater is implemented in both 
> /private/var/containers/Bundle/Application/C860D20D-BAB9-4EC5-B2C3-3A96411E9C7B/Runner.app/Frameworks/video_player.framework/video_player (0x1056aa0e0) and
> /private/var/containers/Bundle/Application/C860D20D-BAB9-4EC5-B2C3-3A96411E9C7B/Runner.app/Frameworks/flutter_ijk.framework/flutter_ijk (0x1050a0b08). 
> One of the two will be used. Which one is undefined.
> 
> objc[35184]: Class FLTVideoPlayer is implemented in both 
> /private/var/containers/Bundle/Application/C860D20D-BAB9-4EC5-B2C3-3A96411E9C7B/Runner.app/Frameworks/video_player.framework/video_player (0x1056aa108) and 
> /private/var/containers/Bundle/Application/C860D20D-BAB9-4EC5-B2C3-3A96411E9C7B/Runner.app/Frameworks/flutter_ijk.framework/flutter_ijk (0x1050a0b30).
> One of the two will be used. Which one is undefined.
> ```
> This happens on iOS projects that include both `video_player` and `flutter_ijk`.

Thank you for your issue, I'll fix this bug soon.
