### ISSUE TITLE
iOS有一些视频只有声音,没有画面

### ISSUE THREAD

**Issue by CaiJingLong** [jadennn/flutter_ijk#7]
无画面的视频:
https://media.w3.org/2010/05/sintel/trailer.mp4
http://img.ksbbs.com/asset/Mon_1703/05cacb4e02f9d9e.mp4

----

有画面的视频
http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
https://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4

---
因为我对于iOS不太熟悉,不知道错误出在哪里,能否帮忙找下问题

**Comment by CaiJingLong** [comment]
并且这些视频下载后放入本地也是同样的情况
使用百度云盘下载的 IjkMediaPlayerDemo工程无画面
但从bilibili 官方源clone编译后的IjkPlayerDemo是可以播放的

猜测是iOS的代码修改部分可能哪里有问题

**Comment by jadennn** [comment]
兄弟，这种情况一般是格式不支持，尝试对比下该项目的根目录config下module-rtsp.sh 和 官方源码的module.sh，看看video解码器的差别，在module-rtsp.sh中加上官方比此项目多的解码器，然后删掉此项目的module.sh，重新将module-rtsp.sh软连接为module.sh，编译再次验证，希望能够生效。。这个项目我抽空会把它全部完善的，只是现在工作太忙了，没时间去弄，谢谢理解

**Comment by jadennn** [comment]
> 并且这些视频下载后放入本地也是同样的情况
> 使用百度云盘下载的 IjkMediaPlayerDemo工程无画面
> 但从bilibili 官方源clone编译后的IjkPlayerDemo是可以播放的
> 
> 猜测是iOS的代码修改部分可能哪里有问题

兄弟，这种情况一般是格式不支持，尝试对比下该项目的根目录config下module-rtsp.sh 和 官方源码的module.sh，看看video解码器的差别，在module-rtsp.sh中加上官方比此项目多的解码器，然后删掉此项目的module.sh，重新将module-rtsp.sh软连接为module.sh，编译再次验证，希望能够生效。。这个项目我抽空会把它全部完善的，只是现在工作太忙了，没时间去弄，谢谢理解

**Comment by CaiJingLong** [comment]
开始我也认为是格式不支持...
所以我昨天开启了所有的支持选项并重新编译 然而发现没用
但是当我拿到 CVPixelBufferRef 后尝试转为UIImage 或是NSData 传输到flutter端  都是可以成功显示为图片的

并且,使用同一个module.sh编译出来的android端是可以成功显示画面的,所以我认为可能并不是这个问题..

**Comment by jadennn** [comment]
> 开始我也认为是格式不支持...
> 所以我昨天开启了所有的支持选项并重新编译 然而发现没用
> 但是当我拿到 CVPixelBufferRef 后尝试转为UIImage 或是NSData 传输到flutter端 都是可以成功显示为图片的
> 
> 并且,使用同一个module.sh编译出来的android端是可以成功显示画面的,所以我认为可能并不是这个问题..

好的，兄弟，谢谢了，这个问题我暂时没空看，不好意思。。并且IOS我也是新手，就搞这个插件看了几天，推荐看看flutter插件camera源码和video_player的源码，我也是模拟那个写的。。实在是抱歉，最近工作天天都是加班到晚上九点以后，没空搞

**Comment by CaiJingLong** [comment]
那你还记得 `createCVPixelBuffer``copyAVFrameToPixelBuffer` 
这几个定义在`ff_play.c`中方法的来源是哪里吗 
你手撸的还是网上找的...

**Comment by jadennn** [comment]
csdn里面有链接


| |
杨玉
邮箱：email_jade@163.com
|

签名由 网易邮箱大师 定制

在2019年03月26日 11:55，Caijinglong 写道：

那你还记得 createCVPixelBuffer``copyAVFrameToPixelBuffer
这几个定义在ff_play.c中方法的来源是哪里吗
你手撸的还是网上找的...

**Comment by Spencer231** [comment]
请问大佬们这个问题是怎么解决的？
出现同样的问题了

**Comment by Spencer231** [comment]
请问大佬们这个问题是怎么解决的？
出现同样的问题了
